language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  
install:
  - "pip install . --use-mirrors"
  - "pip install django>=1.5 psycopg2==2.4.6"

env: 
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
    - REPO="myuser/myrepo"
    - CI_HOME=`pwd`/$REPO
    - PYTHONPATH=$PYTHONPATH:$CI_HOME/tests

before_script:
  - psql -c 'CREATE DATABASE pachyderm;' -U postgres

script:
  - django-admin.py test test_app