language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  
install:
  - "pip install . --use-mirrors"
  - "pip install django>=1.5 psycopg2==2.4.6"

env: DJANGO_SETTINGS_MODULE=test_project.settings

script: django-admin.py test test_app